### ISSUE TITLE
Question about peer:connect

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#10]
Does this event occur both when we connect to a peer and when a peer connects to us? 
https://github.com/streamr-dev/network/blob/e0b512c87b346b3afefd09f464123cc322c4a055/src/connection/Connection.js#L78

**Comment by mirpo** [comment]
https://github.com/libp2p/js-libp2p#libp2ponpeerconnect-peer--

**Comment by harbu** [comment]
On both sides are emitted.
