### ISSUE TITLE
Create graph network structure

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#111]
In the current version, a node that wants to subscribe to a stream will always subscribe to the leader of that stream. This creates a simplified topology, where messages are only passed from leader to subscriber.
 
We need the leader to be able to re-direct the node to subscribe to another subscriber.

**Comment by ptesavol** [comment]
I think the tracker should create the random graph topology for stream S in the following way:

Every time a peer requests peers for Stream S from the tracker of stream S, do:
- Place all peers of stream S in an array (including the leader)
- Take K peers at random from the array and return to the requesting peer

**Comment by harbu** [comment]
Upon further digging into code I agree. Do you however think we should somehow also return the leader if the requesting peer is interested in producing? I was thinking of responding with a random subset of subscribed peers as well as the leader?

**Comment by ptesavol** [comment]
I don't know..returning the leader separately makes it very easy to implement a hacked client that always connects to the leader, and thus gets a lower latency. In the other hand, is there any way to prevent this kind of behaviour? Could we somehow check that a node is connected to exactly those nodes it got from the tracker and to nobody else?
