### ISSUE TITLE
Make nodes send status message to tracker every time their connections change

### ISSUE THREAD

**Issue by ptesavol** [streamr-dev/network-old#171]
The nodes should send status message to the tracker every time they get connected or disconnected to another node or a subscriber of a publisher. Information about the current connections per stream should be added to the "status" message json, for example as "connectedNodes: [{otherNodeId: xxx, otherNodeIp: xxx, direction: outgoing, connectedSince:429874298},..],  connectedSubscribers: [{subscriberIp: "zzzz"}, connectedPublishers: [{publisherIp: "zzzz"}...],  }"

**Comment by mirpo** [comment]
Done in #176
