### ISSUE TITLE
Make tracker keep a map of the current network topology

### ISSUE THREAD

**Issue by ptesavol** [streamr-dev/network-old#172]
The tracker should keep a map of the current network topology per stream. This topology map should be created and updated according to the status messages sent by the nodes. 

The topology map could have a structure like this:

{
streamId: "oiajwfoewji",
nodes:
[{nodeId: "node1", nodeIp: xxx,  connectedNodes: [{otherNodeId: xxx, otherNodeIp: xxx, direction: outgoing, connectedSince:429874298},..], connectedNodes: [{subscriberIp: "zzzz"}, publishers: [{publisherIp: "zzzz"}...],  }, {nodeId: "node2", nodeIp: "yyy", connectedNodes: [ {otherNodeId: xxx, otherNodeIp: xxx, direction: outgoing, connectedSince:429874298},..], subscribers: [{subscriberIp: "zzzz"}, publishers: [{publisherIp: "zzzz"}...],  }},... ] 
}

Notice that you can use the same json format here as in the status messages sent by the nodes.

**Comment by mirpo** [comment]
Done in #176
