### ISSUE TITLE
Ensure `streamr:message-sent` is emitted only when message has been sent

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#20]
Not sure how this `pull-stream` stuff works, is it sync or async. We should verify that event `streamr:message-sent` is emitted once message has been sent.

https://github.com/streamr-dev/network/blob/177cecc7bebc1c88d741030085734c3f78ac17b2/src/connection/Connection.js#L101

**Comment by mirpo** [comment]
asynchronously
