### ISSUE TITLE
Test that multiple streams _actually_ works

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#208]
1st make experiment plan. Need to run in emulator for real scenario.

**Comment by mirpo** [comment]
Further updates for experiments:

1. Run first full experiment
1.1 Run with 4 -> 16 neighbors
1.2 Publisher sends data every 1000, 500, 250, 125, 63, 32, 16, 8 ms

2. Measure amount of received messages
2.1 Create separate stream for reports
2.3 Repost structure - {timestamp, MessageID.toString(), totalNumberOfReceivedMessages}
2.2 Publisher will publish to the network data and send report to the Streamr
2.3 Each node onDataReceved will send report to Streamr

Out of “2” we could calculate:
- How much messages node received (in timeline)
- Time when message X was received by all subscribers (max,min, distribution) (age v2)

3. Test for X streams in network
3.1 subscriber1 and N publishers with N streams
3.1.1 subscriber1 subscribers to N streams, and receives data to all of them
3.1.2 subscriber1 unsubscribers to X streams, and receives data to N - X streams, and not for unsubscribed streams
3.2 run X publishers with X streams, run Y subscribers with randomly subscribe to one stream from X.
3.2.1 Y subscribers should receive data only for one stream (subscribed)

**Comment by harbu** [comment]
Not doing.
