### ISSUE TITLE
Domain language: Node vs. Peer vs. Tracker

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#24]
This might seem like splitting hairs, but it would be good to establish the meaning of the words Peer, Node, and Tracker. Then make sure these terms are used in a consistent manner throughout the codebase.

As I see it:
- Peer is a catch-all term for any actor in the peer-to-peer network?
-  Tracker and Node are specific-kinds of Peers?

**Comment by ptesavol** [comment]
Yes, I share the same view too.

**Comment by harbu** [comment]
Did a quick writeup https://github.com/streamr-dev/network/commit/ad3ff4f3541c3c3cdab7236bd29fa592eb001977.

Feel free to improve.
