### ISSUE TITLE
Consistent naming between code and UML model

### ISSUE THREAD

**Issue by ptesavol** [streamr-dev/network-old#25]
Naming of the classes and public methods should be the same in the code and the UML model. My logic in the naming of classes was that the main classes on the different layers share a common layer-specific ending. On the logic layer the main classes end with "Engine", on the protocol layer with "Handler" and on the connection layer with "Endpoint". This way it is easy to see from the class file alone which layer it belongs to without checking the directory structure.

Is it OK to others if I modify the naming in the code to match that of the UML model?

**Comment by mirpo** [comment]
Maybe let’s keep shorter? And update UML-scheme? No need to have super long names. Classes are already in separate folders - logic/protocol/connection.

**Comment by ptesavol** [comment]
At the moment there are for example, files named /tracker.js and src/logic/Tracker.js
In my opinion it is quite confusing that the only difference in the file names is the use of different case. 

Also from the perspective of self-documenting code it is better to use long, unambiguous names instead of short, ambiguous ones.

**Comment by harbu** [comment]
Feel free to re-open if still issue @ptesavol
