### ISSUE TITLE
npm test fails after a clean git clone

### ISSUE THREAD

**Issue by ptesavol** [streamr-dev/network-old#26]
npm test

> streamr-p2p-network@1.0.0 test /Users/ptesavol/projects/streamr-network
> jest

 FAIL  test/integration/tracker.test.js
  ● Test suite failed to run

    Cannot find module '../../src/logic/peer' from 'tracker.test.js'

      1 | const assert = require('assert')
      2 | const Tracker = require('../../src/logic/Tracker')
    > 3 | const Peer = require('../../src/logic/peer')
        |              ^
      4 | 
      5 | jest.setTimeout(30000)
      6 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.require (test/integration/tracker.test.js:3:14)

 FAIL  test/unit/tracker.test.js
  ● tracker creation › should be able to start and stop successfully

    TypeError: this.connection.on is not a function

      10 |         this.connection = connection
      11 | 
    > 12 |         this.connection.on('streamr:peer:connect', (peer) => this.onNewConnection(peer))
         |                         ^
      13 |         this.connection.on('streamr:message-received', ({
      14 |             sender,
      15 |             message

      at new on (src/protocol/TrackerServer.js:12:25)
      at new Tracker (src/logic/Tracker.js:17:35)
      at Object.done (test/unit/tracker.test.js:11:19)

Test Suites: 2 failed, 2 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.713s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by mirpo** [comment]
yes, I didn't update them after I implemented layers. Working on it in #14
