### ISSUE TITLE
Error: pre-condition: gap overlap in given numbers

### ISSUE THREAD

**Issue by mirpo** [streamr-dev/network-old#282]
When publishing using sequenceNo, DuplicateMessageDetector crashes at some point.

update this code to use sequenceNo++, instead of zero
https://github.com/streamr-dev/network/blob/b1d9b2d66037b1f84bad9d5d1437e2e1f63c184a/bin/publisher.js#L24

**Comment by harbu** [comment]
I believe setting `previousSequenceNo = sequenceNo - 1` fixes this. Tried on my machine and worked, can confirm?
