### ISSUE TITLE
consistent case for filenames

### ISSUE THREAD

**Issue by ptesavol** [streamr-dev/network-old#4]
We should decide consistent case for filenames. At the moment some filenames are written in lower case whereas others are in camel case. I would use lower case for all filenames, as this works cross-platform (yes, some people are still using Windows).

**Comment by harbu** [comment]
Current convention is
- files with a class: `PascalCase.js`
- files with function(s): `camelCase.js`

**Comment by ptesavol** [comment]
OK, let's follow this convention then. In this case tracker.js should be renamed to Tracker.js

**Comment by harbu** [comment]
Good point, fixing.

**Comment by mirpo** [comment]
Already

**Comment by harbu** [comment]
Ah okay

**Comment by mirpo** [comment]
fixed in #13
