### ISSUE TITLE
RTT time calculation

### ISSUE THREAD

**Issue by timoxley** [streamr-dev/network-old#541]
Haven't tested this but this might be a problem:

RTTtime seems like it's likely to be wrong if it receives a pong after it sends followup pings e.g.

```js
// Ping 1 at time 1000ms
ping() {
    // …
    this.rttStart = Date.now() // 1000
    // …
}

// Ping 2 at time 2000ms
ping() {
    // … 
    this.rttStart = Date.now() // 2000
    // …
}

// Pong (responding to Ping 1) at time 2001ms
if (msg === 'pong') { 
    // …
    this.rtt = Date.now() - this.rttStart! // this.rtt = 2001 - 2000 = 1 // 1ms is (very) incorrect, should be 2001ms
}
```

#### See

https://github.com/streamr-dev/network/blob/46903b7e69d807825219846fed6cbf01738916b5/src/connection/Connection.ts#L251-L265

https://github.com/streamr-dev/network/blob/46903b7e69d807825219846fed6cbf01738916b5/src/connection/Connection.ts#L351-L354

**Comment by harbu** [comment]
FYI moved it into a Linear ticket @timoxley https://linear.app/streamr/issue/NET-313/network-rtt-calculation-bug.
