### ISSUE TITLE
Connection should not call dialProtocol every time when sending data

### ISSUE THREAD

**Issue by ptesavol** [streamr-dev/network-old#59]
Currently Connection calls dialProtocol() every time when sending data:
https://github.com/streamr-dev/network/blob/71d555f178ed1e944691e9075b5299f0ee999813/src/connection/Connection.js#L38

This should be replaced with the use of reusable "pull-pushable" as done in the libp2p example at https://github.com/libp2p/js-libp2p/blob/e0520213979abcc5e58330c83b784c6b8d596500/examples/chat/src/dialer.js#L59

**Comment by mirpo** [comment]
not actual
