### ISSUE TITLE
Remove hardcoding of single Tracker

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#69]
Currently the codebase works on the assumption that there is a single tracker with a specific private key, hostname, and port. This is good for now.

First step towards generalization would be to keep the assumption that there is a single tracker, but allow the private key, port, and hostname to be different. 

Things that need to be changed
- `utils.js#BOOTNODES` constant must be removed and bootstrap tracker given as parameter.
- `utils.js#isTracker` - we need a mechanism to detect whether a peer is a tracker or not. Current mechanism is hardcording.

**Comment by harbu** [comment]
Actually maybe DHT will fix this whole issue?

**Comment by mirpo** [comment]
anyway it'll be some combination:
- fixed list of out trackers (BOOTNODES), in future this list will contain some public IP addresses, with their private keys and etc.
- DHT for all other nodes/trackers

so let's postpone it for a while

**Comment by harbu** [comment]
This will be fixed with DHT (issue does not yet exist)
