### ISSUE TITLE
EADDRINUSE in tests, probably a bug in libp2p

### ISSUE THREAD

**Issue by ptesavol** [streamr-dev/network-old#71]
This only happens occasionally. Apparently publisher.test.js exits before LibP2p has closed its listening port, and  tracker.test.js complains about EADDRINUSE.

I'll change the port in tracker.test.js to 30336 just to get the tests go through, but need to keep this in mind, probably there is a bug in LibP2p that calls the final callback before the listening socket has actually closed.

Test output:

 PASS  test/unit/topology.test.js
 PASS  test/unit/encoder.test.js
 PASS  test/unit/publisher.test.js
 FAIL  test/unit/tracker.test.js
  ● tracker creation › should be able to start and stop successfully

    listen EADDRINUSE 127.0.0.1:30335

**Comment by mirpo** [comment]
we are running in travis ci those tests, so maybe problem with your local env.

**Comment by ptesavol** [comment]
Yes,  probably this has to do with my machine being too slow in closing connections, and this bug can only be noticed on slow/overloaded machines. Probably Libp2p does not really wait until the server socket really closes but instead fires the callback assuming that the closing of the socket will happen fast enough.

**Comment by harbu** [comment]
Feel free to re-open this @ptesavol if still happening. Apparently there was some issue with closing ports that has been resolved.
