### ISSUE TITLE
createNode() and this.isStarted

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#9]
I think an `await` is needed here, but not possible because constructor cannot be async?
https://github.com/streamr-dev/network/blob/e0b512c87b346b3afefd09f464123cc322c4a055/src/connection/Connection.js#L24

Maybe we should export an async function from this module that acts as the "constructor" of this class for the outside world. That async would return a Promise with the Connection object instance as its value. We could probably get rid of `this.isStarted` variable while doing this.

Let's discuss if this make sense or not.

**Comment by ptesavol** [comment]
I agree that as little as possible should be done in constructors in javascript because async is not possible. Do add an async function to do the initialisation.
