### ISSUE TITLE
Permission checking

### ISSUE THREAD

**Issue by harbu** [streamr-dev/network-old#96]
Do we need permission checking on the network layer?

As I understand it, the first version of the network will run in our private environment with partial centralization. Thus we can leave permission checking (via E&E permissions API) to the broker layer.

In future with full centralization, we will no longer have a centralized API to check permissions from. My understanding is that data will be encrypted so don't really need permission checking for securing data. It is more fore ensuring that Producers are who they claim to be (because it costs them to produce).

**Comment by hpihkala** [comment]
@harbu In the future decentralized version there will still be a (decentralized) place to read permissions from, such as a smart contract.

I think we need something along the lines of a `validate(msg)` function, which would check:
- Message signature (future feature) is valid
- Producer has permission to produce to this stream
- Check producer DATA balance, stake placed, etc. depending on incentive mechanism (future feature)

The remaining question is whether this should be on the network layer or broker layer.

Let's assume it's on the broker layer. Would it mean that nodes are then easily able to spoof messages to streams, as no checking occurs in the node-to-node interaction? If yes, we should move/add message validation to the network layer.

**Comment by harbu** [comment]
Discussion is done.
